import logging
from datetime import timedelta

DEBUG = True
TESTING = True
SECRET_KEY = "fe339b49-d1c9-499d-a6e1-193124697c9b"
SESSION_TYPE = "sqlalchemy"
SESSION_PERMANENT = True
PERMANENT_SESSION_LIFETIME = timedelta(days=31)
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = True
JWT_ALGORITHM = "HS256"
COMPRESSOR_DEBUG = False
SQLALCHEMY_DATABASE_URI = "sqlite:///database.db"
SQLALCHEMY_ECHO = True
MAX_COOKIE_SIZE = 4093
LOGGER_LEVEL = logging.DEBUG
CACHE_TYPE = "SimpleCache"
CACHE_DEFAULT_TIMEOUT = 300
CACHE_THRESHOLD = 5000
CACHE_IGNORE_ERRORS = True
