name: build_and_deploy_services

on:
  workflow_call:
    secrets:
      DOCKER_AUTH_TOKEN:
        description: 'Required docker auth token'
        required: true
  push:
    branches:
      - main

env:
  NODE_ENV: 'dev'
  SERVICE_NAME: 'clan.sports-services'
  DOCKER_USERNAME: 'codigouranio'
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: restore_or_save_cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-v1-dependencies-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v1-dependencies-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
      - name: Build and push services
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: codigouranio/clan-sports-app:latest
      - name: Create deploy file
        env:
          CONTAINER_IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
        run: |
          zip -rj deploy.zip docker-compose.yml
      - uses: actions/upload-artifact@v4
        with:
          name: deploy.zip
          path: deploy.zip